#!/bin/bash

g++ -c -fPIC -I${ONESEIS_HOME}/core/include -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux oneseismic_DecoderJNI.cpp -o decoder.o

g++ -shared -fPIC -o libdecoder.so decoder.o decoder.cpp.o
