/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oneseismic_DecoderJNI */

#ifndef _Included_oneseismic_DecoderJNI
#define _Included_oneseismic_DecoderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oneseismic_DecoderJNI
 * Method:    create_decoder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_oneseismic_DecoderJNI_create_1decoder
  (JNIEnv *, jobject);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    status
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_status
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    free_decoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_free_1decoder
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    decode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_decode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
