/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oneseismic_DecoderJNI */

#ifndef _Included_oneseismic_DecoderJNI
#define _Included_oneseismic_DecoderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oneseismic_DecoderJNI
 * Method:    create_decoder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_oneseismic_DecoderJNI_create_1decoder
  (JNIEnv *, jobject);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    buffer_and_process
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_buffer_1and_1process
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    header
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_header
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    header_attributes
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_oneseismic_DecoderJNI_header_1attributes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    header_shape
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_oneseismic_DecoderJNI_header_1shape
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    register_writer
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_register_1writer
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    status
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_status
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    free_decoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_free_1decoder
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oneseismic_DecoderJNI
 * Method:    decode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oneseismic_DecoderJNI_decode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
